networks:
    time-clock-network:
        driver: bridge

volumes:
    db_data:


services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: time-clock
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - time-clock-network
        env_file:
            - .env

    nginx:
        image: nginx:stable-alpine
        container_name: time-clock-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - time-clock-network

    mysql:
        image: mysql:8.3.0
        container_name: time-clock-mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - time-clock-network
        ports:
            - "3306:3306"
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: time-clock-phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql
        ports:
            - "8080:80"
        networks:
            - time-clock-network
        restart: unless-stopped

    redis:
        image: redis:latest
        container_name: time-clock-redis
        ports:
            - "6379:6379"
        networks:
            - time-clock-network
        restart: unless-stopped
